### ISSUE TITLE
Version 3.0.0 and later is no OSGi bundle anymore

### ISSUE THREAD

**Issue by Lana11s** [graphql-java/java-dataloader#106]
**Describe the bug**
Since version 3.0.0 the java-dataloader is no valid OSGi bundle anymore.
The MANIFEST.MF file does not contain the required entries anymore.

Version 2.2.3 was a valid bundle and was running fine in an OSGi runtime.

**To Reproduce**
Load java-dataloader in an OSGi runtime, like Eclipse or Apache Felix.

**Expected**
Valid OSGi bundle with valid import/export.

old MANIFEST.MF:
```
Manifest-Version: 1.0
Export-Package: org.dataloader;version="2.2.3";uses:="org.dataloader.s
 tats",org.dataloader.impl;version="2.2.3";uses:="org.dataloader",org.
 dataloader.stats;version="2.2.3"
Bundle-SymbolicName: org.dataloader.java-dataloader
Bundle-Version: 2.2.3
Bundle-Name: java-dataloader
Bundle-ManifestVersion: 2
Bnd-LastModified: 1566716677000
Import-Package: org.dataloader;version="[2.2,3)",org.dataloader.impl;v
 ersion="[2.2,3)",org.dataloader.stats;version="[2.2,3)"
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"
Created-By: 1.8.0_212 (AdoptOpenJDK)
Tool: Bnd-3.2.0.201605172007
```

new MANIFEST.MF:
```
Manifest-Version: 1.0
Automatic-Module-Name: com.graphql-java
```

**Comment by bbakerman** [comment]
A PR maybe to make it might help.  I dont use OSGi any more (I swore off the stuff 5 years ago ;)

**Comment by Lana11s** [comment]
Hello @bbakerman, I created a PR here: https://github.com/graphql-java/java-dataloader/pull/113
