### ISSUE TITLE
Automatic Module Name clashes with graphql-java Module

### ISSUE THREAD

**Issue by brianoliver** [graphql-java/java-dataloader#110]
In a modular java system it's not possible to use the graphql-java module and the java-loader as that have the same automatic module name 'com.graphqljava'

```
Automatic-Module-Name: com.graphqljava
```

I think the automatic module name for the java-dataloader module should be:

```
Automatic-Module-Name: org.dataloader
```

To match the package names.

**Comment by hanson76** [comment]
And comments on this? 
This is bit of a problem, we can't upgrade GraphQL-Java past version 17 as it is now.

**Comment by bbakerman** [comment]
By all means - can someone please make a PR and change it to `org.dataloader`
