### ISSUE TITLE
Per Request loaders with graphql

### ISSUE THREAD

**Issue by chrischandler25** [graphql-java/java-dataloader#19]
Hi

I'm struggling to follow the documentation as to how I can implement per request data loaders. 
The docs at [http://graphql-java.readthedocs.io/en/v7/batching.html] suggest creating a single instance schema up front as this is a somewhat expensive operation, and then creating dataloaders per request.

Given that runtime wiring must be provided at time of schema creation, and in the runtime wiring data fetchers reference the data loaders (as per the docs), I'm not sure I can then create these data loaders later at the time of an individual request.

The only solution I could think of is to include the DataLoaderRegistry in my context object, which is then available at time of DataFetcher execution, in order to get a reference for the correct data loader instance.

I'm not sure if I've explained this well, but I'm surprised I haven't been able to find an example as this seems to be something that would be a common issue.

Regards 
Chris

**Comment by kaqqao** [comment]
I'm pretty sure `DataLoaderRegistry` in the context is the intended way to go.

**Comment by bbakerman** [comment]
>  DataLoaderRegistry in my context object

Yup thats definitely the way to go

DataLoaders are caches and hence stateful objects

Unless you want to cache across requests (trust me you probably should not but of course it depends) then you must create the data loaders per request.

The graphql  context is where you add per request things

**Comment by bbakerman** [comment]
See https://github.com/graphql-java/graphql-java-http-example/blob/master/src/main/java/com/graphql/example/http/StarWarsWiring.java
