### ISSUE TITLE
Usage without GraphQL

### ISSUE THREAD

**Issue by PepijnK** [graphql-java/java-dataloader#22]
Hello,

I want to use this library as a layer to optimize loading the graph of a good ol' REST service. We don't have a GraphQL API (yet), however the parallel provisioning from DataLoader seems useful as it also provides the batching and per-request caching. However I can't really find a guideline how to call a chain of nested dataloaders as if it is instrumented by a GraphQL library to compose a response with nested (multiple resolving) objects.

Would it be possible to extend the examples with this use-case?

**Comment by bbakerman** [comment]
Sorry only just saw this issue.  I am not sure there is much to add in the base library.

The `org.dataloader.DataLoaderRegistry` is designed in this lib to help you track multiple DataLoader types and call "dispatch" on all of them.

But exactly when the right top to call dispatch is now up to you.  DataLoader does not get into how you compose your results (like graphql does).  It just says for a list of keys X give me a list of values Y.

**Comment by aisensiy** [comment]
I have a similar question about this and I put it in discussion https://github.com/graphql-java/java-dataloader/discussions/114.
