### ISSUE TITLE
2.2.0 doesn't have checksums for .pom files in Maven Central

### ISSUE THREAD

**Issue by MarcBridner** [graphql-java/java-dataloader#35]
Hi

Version 2.2.0 doesn't have checksums for the .pom files in Maven Central which causes issues when trying to import into a local repository.

http://central.maven.org/maven2/com/graphql-java/java-dataloader/2.2.0/

**Comment by MarcBridner** [comment]
2.2.1 fixes it

**Comment by bbakerman** [comment]
Yeah I just made a release - no different to the others ones.  Maybe BinTray was having a bad day
