### ISSUE TITLE
Create a sample application that demonstrates java-dataloader and its efficiency

### ISSUE THREAD

**Issue by bbakerman** [graphql-java/java-dataloader#4]
This helps shape out the library better and gives people something to investigate

**Comment by raderio** [comment]
+1

**Comment by bbakerman** [comment]
See https://github.com/graphql-java/graphql-java-http-example

**Comment by mudlee** [comment]
Hi, sorry for posting a question here, but the example posted here does not work for me.
I use the latest graphql-java.

My problem is, that in the datafetcher when I try to get my object with dataLoader.load, it always return null, despite the data is available in the loader itself.

I put a println 

- to the datafetcher's get method
- to the batchloader's load method
- to the repository that's used by the batchloader

and I see that:
`user is null: true
user is null: true
user is null: true
LOADING
FINDING
user is null: true
user is null: true
`

The context set correctly, dataloaders available in the fetchers, dataloader registry is put to a DataLoaderDispatcherInstrumentation, the datafetcher returns a CompletableFuture and I use AsyncExecutionStrategy for queryExecutionStrategy.

What am I missing?

**Comment by mudlee** [comment]
OK, I found, that was a misuse of CompletableFuture, but now I'm in the middle of "The size of the promised values MUST be the same size as the key list" problem.
