### ISSUE TITLE
keyContext merge function under batching

### ISSUE THREAD

**Issue by alon-hagshury** [graphql-java/java-dataloader#42]
I'm very excited by your work and wonder if i could get your approval on adding support for keyContext merging while batching the same key with different context. I'm using the keyContexts of BatchLoaderEnvironment to ship the selection fields for a key. Some queries might have the same key with different selection fields and the batching mechanism in DataLoaderHelper's mkKeyContextMap method overrides the context with the latest context encountered for that key. I'll be glad if mkKeyContextMap be handed a function to handle a merge in such cases.

**Comment by kaqqao** [comment]
@alon-hagshury Just wondering why you closed the issue?

**Comment by alon-hagshury** [comment]
@kaqqao I guess the batching mechanism wasn't intended to tackle the same key with different contexts, hence I decided to pick one of the 2 directions: (1) avoid the context to carry selection fields (2) merge the context right ahead in my app, before batching take place.
