### ISSUE TITLE
How do I store the cache to a remote server

### ISSUE THREAD

**Issue by lyzq** [graphql-java/java-dataloader#59]
I want to store the cache to a remote server, and i implement CacheMap.
Then i got :
Serialized class java.util.concurrent.CompletableFuture must implement java.io.Serializable

**Comment by bbakerman** [comment]
Yup there is a design fault in the current code, that is what looks like `CacheMap<U, V>` is in fact `CacheMap<U, CompletableFuture<V>>`

And   `CompletableFuture` is never going to be able to be serialised.

This has caught other people out.  Our cache is in fact previously completed CFs -> values and not the values themselves.

This needs a major refactpr to fix

**Comment by bbakerman** [comment]
See https://github.com/graphql-java/java-dataloader/issues/45

**Comment by bbakerman** [comment]
This PR attempts to improve this situation

https://github.com/graphql-java/java-dataloader/pull/88
